import AppProvider from "@/context/AppProvider";
import "./globals.css";
import { Roboto } from "next/font/google";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Auth with Firebase",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppProvider>
          <Navbar />
          <main className="sm:px-0 container px-5 mx-auto">{children}</main>
          <ToastContainer />
        </AppProvider>
      </body>
    </html>
  );
}
